Saelker\MigrationsBundle\Entity\Migration:
    type: entity
    table: migration
    repositoryClass: Saelker\MigrationsBundle\Repository\MigrationRepository
    indexes:
        directory_index:
            columns: [ directory ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        identifier:
            type: string
            length: 255
        directory:
            type: string
            length: 255
        createdAt:
            type: datetime
            column: createdAt
    lifecycleCallbacks: {  }
