services:
    _defaults:
        public: true
        autowire: true

    Saelker\MigrationsBundle\MigrationsManager: ~

    Saelker\MigrationsBundle\Helper\:
        resource: '../../Helper'

    Saelker\MigrationsBundle\Command\:
        resource: '../../Command'
        tags: ['console.command']