<?php

namespace Saelker\MigrationsBundle\Repository;

use Saelker\MigrationsBundle\Entity\Migration;

/**
 * MigrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MigrationRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @param $directory
	 * @return Migration
	 */
	public function getLatestMigration($directory)
	{
		return $this
			->createQueryBuilder('m')
			->andWhere('m.directory = :directory')
			->setMaxResults(1)
			->orderBy('m.identifier', 'DESC')
			->setParameter('directory', $directory)
			->getQuery()
			->getOneOrNullResult();
	}
}
