<?php

namespace Saelker\MigrationsBundle\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\QueryBuilder;
use Saelker\MigrationsBundle\Entity\Migration;
use Saelker\MigrationsBundle\Util\ImportFile;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Finder\Finder;

/**
 * MigrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MigrationRepository extends ServiceEntityRepository
{
	/**
	 * MigrationRepository constructor.
	 *
	 * @param ManagerRegistry $registry
	 */
	public function __construct(ManagerRegistry $registry)
	{
		parent::__construct($registry, Migration::class);
	}

	/**
	 * @return QueryBuilder
	 */
	public function getQueryBuilder(): QueryBuilder
	{
		return $this
			->createQueryBuilder('m');
	}

	/**
	 * @param $directory
	 *
	 * @return Migration
	 *
	 * @throws \Doctrine\ORM\NonUniqueResultException
	 */
	public function getLatestMigration($directory)
	{
		return $this
			->getIdentifierQueryBuilder($directory)
			->setMaxResults(1)
			->getQuery()
			->getOneOrNullResult();
	}

	/**
	 * @param $directory
	 *
	 * @return array
	 */
	public function getAllMigrationIdentifiers($directory)
	{
		return $this
			->getIdentifierQueryBuilder($directory)
			->select('m.identifier')
			->getQuery()
			->getResult();
	}

	/**
	 * @return mixed
	 */
	public function getLatestSequence()
	{
		try {
			$sequence = $this
				->getQueryBuilder()
				->select('MAX(m.sequence) as sequence')
				->getQuery()
				->getOneOrNullResult();

			$sequence = $sequence['sequence'];
		} catch (\Exception $e) {
			$sequence = 0;
		}

		return $sequence;
	}

	/**
	 * @param $directory
	 *
	 * @return integer
	 */
	public function getNextIdentifier($directory)
	{
		$currentIdentifier = (new \DateTime())->format('YmdHis');

		$sort = function (\SplFileInfo $a, \SplFileInfo $b) {
			return strcmp($b->getRealPath(), $a->getRealPath());
		};

		$finder = new Finder();
		$finder
			->files()
			->in($directory)
			->name('/V_\d*_.*/')
			->sort($sort);


		if ($finder->getIterator()->current()) {
			$lastFile = new ImportFile($finder->getIterator()->current(), null, null);
			$newNumber = substr($lastFile->getFileIdentifier(), 0, -3) == $currentIdentifier ? intval(substr($lastFile->getFileIdentifier(), -3)) + 1 : 1;
		} else {
			$newNumber = 1;
		}

		return $currentIdentifier . sprintf('%03d', $newNumber);
	}

	/**
	 * @param $directory
	 *
	 * @return \Doctrine\ORM\QueryBuilder
	 */
	private function getIdentifierQueryBuilder($directory)
	{
		return $this
			->getQueryBuilder()
			->andWhere('m.directory = :directory')
			->orderBy('m.identifier', 'DESC')
			->setParameter('directory', $directory);
	}

	/**
	 * @param int $sequence
	 */
	public function deleteFromSequence(int $sequence): void
	{
		$this
			->getEntityManager()
			->createQueryBuilder()
			->delete(Migration::class, 'm')
			->andWhere('m.sequence = :sequenceFilter')
			->setParameter('sequenceFilter', $sequence)
			->getQuery()
			->execute();
	}
}
